version: "3.9"
services:
  elasticsearch:
    container_name: uli-elasticsearch
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic

  kibana:
    container_name: uli-kibana
    image: kibana:8.2.2
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

  api:
    container_name: uli-nodejs
    restart: always
    build:
      context: .
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
      - ES_HOST=elasticsearch
    command: yarn run nodemon ./api/index.js
    volumes:
      - .:/usr/src/app/
      - ./error.log:/usr/src/app/error.log
      - /usr/src/app/node_modules/
    depends_on:
      - kibana
    networks:
      - elastic
  
volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: uli-elastic
    driver: bridge
  