version: "3.9"
services:
  backend:
    container_name: uli_nodejs
    restart: always
    build:
      context: .
    ports:
    - "80:3000"
    - "5678:5678"
    - "9229:9229"
    environment:
    - ES_HOST=elasticsearch
    - NODE_ENV=development
    - SERVER_HOST=192.168.1.74
    command: yarn dev
    volumes:
    - .:/usr/src/app/
    - ./error.log:/usr/src/app/error.log
    - /usr/src/app/node_modules/
    depends_on:
    - elasticsearch
  elasticsearch:
      container_name: uli_elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
      environment:
      - node.name=uli-es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - SERVER_HOST=192.168.1.74
      volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./docker-data-volumes/elasticsearch:/usr/share/elasticsearch/data
      - ./esbackup:/usr/share/elasticsearch/esbackup
      ports:
      - "9200:9200"
  kibana:
      container_name: uli_kibana
      depends_on:
      - elasticsearch  
      image: docker.elastic.co/kibana/kibana:7.10.1
      ports:
      - 5601:5601
      volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml           
volumes:
  esdata:
    driver: local
 