const standardResources = [
  "Property",
  "Member",
  "Office",
  "Contacts",
  "Media",
  "HistoryTransactional",
  "ContactListings",
  "InternetTracking",
  "SavedSearch",
  "OpenHouse",
  "Prospecting",
  "Queue",
  "Rules",
  "Teams",
  "Showing",
  "TeamMembers",
  "OUID",
  "ContactListingNotes",
  "OtherPhone",
  "PropertyGreenVerification",
  "PropertyPowerProduction",
  "PropertyRooms",
  "PropertyUnitTypes",
  "SocialMedia",
];

const standardResourcesUrls = {
  Property: "https://ddwiki.reso.org/display/DDW17/Property+Resource",
  Member: "https://ddwiki.reso.org/display/DDW17/Member+Resource",
  Office: "https://ddwiki.reso.org/display/DDW17/Office+Resource",
  Contacts: "https://ddwiki.reso.org/display/DDW17/Contacts+Resource",
  Media: "https://ddwiki.reso.org/display/DDW17/Media+Resource",
  HistoryTransactional: "https://ddwiki.reso.org/display/DDW17/HistoryTransactional+Resource",
  ContactListings: "https://ddwiki.reso.org/display/DDW17/ContactListings+Resource",
  InternetTracking: "https://ddwiki.reso.org/display/DDW17/InternetTracking+Resource",
  SavedSearch: "https://ddwiki.reso.org/display/DDW17/SavedSearch+Resource",
  OpenHouse: "https://ddwiki.reso.org/display/DDW17/OpenHouse+Resource",
  Prospecting: "https://ddwiki.reso.org/display/DDW17/Prospecting+Resource",
  Queue: "https://ddwiki.reso.org/display/DDW17/Queue+Resource",
  Rules: "https://ddwiki.reso.org/display/DDW17/Rules+Resource",
  Teams: "https://ddwiki.reso.org/display/DDW17/Teams+Resource",
  Showing: "https://ddwiki.reso.org/display/DDW17/Showing+Resource",
  TeamMembers: "https://ddwiki.reso.org/display/DDW17/TeamMembers+Resource",
  OUID: "https://ddwiki.reso.org/display/DDW17/OUID+Resource",
  ContactListingNotes: "https://ddwiki.reso.org/display/DDW17/ContactListingNotes+Resource",
  OtherPhone: "https://ddwiki.reso.org/display/DDW17/OtherPhone+Resource",
  PropertyGreenVerification: "https://ddwiki.reso.org/display/DDW17/PropertyGreenVerification+Resource",
  PropertyPowerProduction: "https://ddwiki.reso.org/display/DDW17/PropertyPowerProduction+Resource",
  PropertyRooms: "https://ddwiki.reso.org/display/DDW17/PropertyRooms+Resource",
  PropertyUnitTypes: "https://ddwiki.reso.org/display/DDW17/PropertyUnitTypes+Resource",
  SocialMedia: "https://ddwiki.reso.org/display/DDW17/SocialMedia+Resource",
};

module.exports = {
  standardResources,
  standardResourcesUrls
};
