export const resourcesByOrder = [
  "Property",
  "Member",
  "Media",
  "Office",
  "Contacts",
  "HistoryTransactional",
  "ContactListings",
  "InternetTracking",
  "SavedSearch",
  "OpenHouse",
  "Prospecting",
  "Queue",
  "Rules",
  "Showing",
  "Teams",
  "TeamMembers",
  "OUID",
  "ContactListingNotes",
  "OtherPhone",
  "PropertyGreenVerification",
  "PropertyPowerProduction",
  "Room",
  "PropertyUnitTypes",
  "SocialMedia",
  "Lookup Fields and Values",
  "Standard Relationships",
  "Deprecated Fields",
  "Deprecated Lookup Values",
  "IDX Payloads",
  "Version Info",
  "Worksheet Summary",
];

export const RESOURCES = {
  reso: [
    "Property",
    "Member",
    "Office",
    "Contacts",
    "ContactListings",
    "HistoryTransactional",
    "InternetTracking",
    "Media",
    "OpenHouse",
    "OUID",
    "Prospecting",
    "Queue",
    "Rules",
    "SavedSearch",
    "Showing",
    "Teams",
    "TeamMembers",
    "ContactListingNotes",
    "OtherPhone",
    "PropertyGreenVerification",
    "PropertyPowerProduction",
    "PropertyRooms",
    "PropertyUnitTypes",
    "SocialMedia",
  ],
  idx: [
    "Property",
    "Member",
    "Office",
    "Media",
    "OpenHouse",
    "PropertyGreenVerification",
  ],
};
